### ISSUE TITLE
Incompatible with Angular Ivy

### ISSUE THREAD

**Issue by ciriousjoker** [puckowski/deepequalspure#3]
```
Error: node_modules/ngx-deep-equals-pure/lib/ngx-deep-equals-pure.service.d.ts:2:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

This likely means that the library (ngx-deep-equals-pure) which declares NgxDeepEqualsPureService has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

2 export declare class NgxDeepEqualsPureService {
```

This issue persists in any combination of library version 0.2.5/0.3.0/0.4.1 and Angular 11/12.

**Comment by puckowski** [comment]
Here is an example of version 0.4.1 working in an Angular 12 project where Ivy is enabled:
[Angular 12 Stackblitz](https://stackblitz.com/edit/angular-ivy-he6xbd?file=src/app/app.component.ts)

tsconfig.json snippet:
```
"angularCompilerOptions": {
    "enableIvy": true,
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true
  }
```

Please follow the configuration of the Stackblitz project above or post a link to a public repository that reproduces your issue.

I will close this issue if there is no response in a week.

**Comment by ciriousjoker** [comment]
Thanks for your effort. I can't test it anytime soon as I downgraded to Angular 11 and am currently on vacation. Once I try it out, I'll update this issue.
