### ISSUE TITLE
Usage example in README

### ISSUE THREAD

**Issue by Helveg** [puckowski/deepequalspure#5]
I had to search a bit through the example app to figure out how to use this, I could PR a minimal example to the README if you want? Could the `deepEquals` function also be factored out of the service to be used as a standalone function?

**Comment by puckowski** [comment]
Added to README.md

```
# NgxDeepEqualsPure

Note:
- Please use version 0.3.0+ for Angular 12.0+ projects. 
- Please use version 0.2.5 for projects using Angular 11.0 and below. 
- Version 0.4.0+ supports use in Web Workers.
- Version 0.4.3+ supports Standalone Components.
- Version 0.4.2 is malformed and should not be used.
```

and

```
## Usage

In the appropriate module, such as ```AppModule```, add the following to ```providers```:

```javascript
providers: [NgxDeepEqualsPureService],
```

In a component part of a module where NgxDeepEqualsPureService is provided, inject the deep equals service in the constructor like so:

```javascript
constructor(private ngxDeepEquals: NgxDeepEqualsPureService) {
```

Then use NgxDeepEqualsPure like so:

```javascript
this.ngxDeepEquals.deepEquals(this.obj1, this.obj2);
```

Alternatively, construct a standalone component like the following:

```javascript
import { Component } from '@angular/core';
import { NgxDeepEqualsPureModule, NgxDeepEqualsPureService } from 'NgxDeepEqualsPure';

@Component({
  selector: 'app-standalone-test',
  templateUrl: './standalone-test.component.html',
  styleUrls: ['./standalone-test.component.scss'],
  standalone: true,
  imports: [NgxDeepEqualsPureModule]
})
export class StandaloneTestComponent {

  private obj8: any = { b: 'a', c: 2 };
  private obj9: any = { c: 2, b: 'a' };

  public isStandaloneMatch: boolean;

  constructor(private ngxDeepEquals: NgxDeepEqualsPureService) {
    this.isStandaloneMatch = this.ngxDeepEquals.deepEquals(this.obj8, this.obj9);
  }
}
```
```

**Comment by puckowski** [comment]
Version 0.4.3+ will support Standalone Components (tested 04/19/2023 20:36) and use in Angular Modules. 

User of package can extract the necessary function(s) from ```NgxDeepEqualsPureService``` manually if they use to wish functionality without a service and without a module. That process would be straightforward, but usage of service/module is recommended.
