### ISSUE TITLE
Version 0.4.3 misses Angular 16 support

### ISSUE THREAD

**Issue by barsurfer** [puckowski/deepequalspure#6]
Can't use 0.4.3 with angular 16.0.2  and received the following error:

`npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: @angular/common@16.0.2
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^16.0.2" from the root project
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
`

Is it possible to add the support?

**Comment by puckowski** [comment]
Version 0.5.0+ supports Angular 16.0.0+.

https://stackblitz.com/edit/stackblitz-starters-me7suo?file=src%2Fmain.ts

@barsurfer

**Comment by barsurfer** [comment]
Thank you for your rapid response
